import { rejectAfter } from "../../utils/resolve";
-- a
await=rejectAfter(new Error("ERROR!"), 1)
  -- failed
-- b
